// <auto-generated />
using MTG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTG.Migrations
{
    [DbContext(typeof(CardContext))]
    partial class CardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MTG.Models.Card", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CMC")
                        .HasMaxLength(20);

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("colorIdentity")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasMaxLength(5);

                    b.Property<string>("imgURL")
                        .IsRequired()
                        .HasMaxLength(600);

                    b.Property<string>("manaCost")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("power")
                        .HasMaxLength(5);

                    b.Property<string>("rarity")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("set")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("superType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("toughness")
                        .HasMaxLength(5);

                    b.Property<string>("typePermanent")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
